/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        globe: "#1C1B20",
        island: "#24232A",
        on_island: "#313038",
        on_island_hover: "#3B3A42",
        coloured: "#775CDF",
        divider_light: "#303030",
        divider_dark: "#24232A",
        overlay_light: "rgba(0, 0, 0, 0.4)",
        overlay_dark: "rgba(0, 0, 0, 0.6)",
        txt_primary: "#FFFFFF",
        txt_secondary: "#E2E2E2",
        txt_tertiary: "#9F9F9F",
        txt_primary_inverse_light: "#FFFFFF",
        txt_primary_inverse_dark: "#1C1B20",
        txt_accent_primary: "#B19CFF",
        txt_accent_secondary: "#B5DB1C",
        icon_primary: "#FFFFFF",
        icon_secondary: "#E2E2E2",
        icon_tertiary: "#9F9F9F",
        icon_primary_inverse_light: "#FFFFFF",
        icon_primary_inverse_dark: "#1C1B20",
        icon_accent_primary: "#775CDF",
        icon_accent_secondary: "#B5DB1C",
        btn_primary: "#775CDF",
        btn_primary_on_tap: "#6247CF",
        btn_secondary: "#B5DB1C",
        btn_secondary_on_tap: "#7E9E00",
        btn_tertiary: "#313038",
        btn_tertiary_on_tap: "#FFFFFF",
        btn_primary_inverse_dark: "#1C1B20",
        disabled: "#312F37",
        txt_btn_dark: "#1C1B20",
        txt_btn_light: "#FFFFFF",
        status_danger: "#EB3333",
        status_success: "#1CDB2F",
        status_warning: "#F5CB3E",
      },
      fontFamily:{
        DM_sans: ["DM Sans"],
      }
    },
  },
  plugins: [],
};
